import {
  computeNextExpectedRefresh as computeNextExpectedRefreshModule,
  isBriefSnapshotCompatible as isBriefSnapshotCompatibleModule,
} from '../domain/market-products';
import { ensureMarketProductSchema as ensureMarketProductSchemaGuard } from '../db/schema';
import {
  insertMarketEvents as insertMarketEventsData,
} from '../data/market-events';
import {
  buildOpportunityLedgerProjection as buildOpportunityLedgerProjectionData,
  insertOpportunityItemLedgerRow as insertOpportunityItemLedgerRowData,
  insertOpportunityLedgerRow as insertOpportunityLedgerRowData,
} from '../data/market-ledger';
import {
  claimMarketRefreshRun as claimMarketRefreshRunData,
  computeFreshnessSloWindow as computeFreshnessSloWindowData,
  recordMarketRefreshRunFinish as recordMarketRefreshRunFinishData,
  recordMarketRefreshRunStart as recordMarketRefreshRunStartData,
  resolveLatestRefreshTimestamp as resolveLatestRefreshTimestampData,
} from '../data/market-refresh';
import {
  fetchCalibrationSnapshotAtOrBefore as fetchCalibrationSnapshotAtOrBeforeData,
  fetchDecisionImpactSnapshotAtOrBefore as fetchDecisionImpactSnapshotAtOrBeforeData,
  fetchLatestCalibrationSnapshot as fetchLatestCalibrationSnapshotData,
  fetchLatestConsistencyCheck as fetchLatestConsistencyCheckData,
  storeBriefSnapshot as storeBriefSnapshotData,
  storeCalibrationSnapshot as storeCalibrationSnapshotData,
  storeConsistencyCheck as storeConsistencyCheckData,
  storeDecisionImpactSnapshot as storeDecisionImpactSnapshotData,
  storeOpportunitySnapshot as storeOpportunitySnapshotData,
} from '../data/market-snapshots';
import {
  computeUtilityFunnelSummary as computeUtilityFunnelSummaryData,
  insertUtilityEvent as insertUtilityEventData,
} from '../data/market-utility';
import { constantTimeEquals as constantTimeCompare, enforceAdminAuth as enforceAdminRouteAuth } from '../lib/security';
import {
  finalizeDigestDeliveryFailure as finalizeDigestDeliveryFailureService,
  finalizeDigestDeliverySent as finalizeDigestDeliverySentService,
  reserveDigestDeliveryForSubscriber as reserveDigestDeliveryForSubscriberService,
  sendDigestToSubscriber as sendDigestToSubscriberService,
} from '../services/market-digest';
import * as legacy from '../runtime/legacy';

export function createRouteDeps() {
  return {
    INDICATOR_FREQUENCY_HINTS: legacy.INDICATOR_FREQUENCY_HINTS,
    addCalendarDays: legacy.addCalendarDays,
    applyCrossHorizonActionabilityOverride: legacy.applyCrossHorizonActionabilityOverride,
    asIsoDate: legacy.asIsoDate,
    asIsoDateTime: legacy.asIsoDateTime,
    buildBriefFallbackSnapshot: legacy.buildBriefFallbackSnapshot,
    buildBriefSnapshot: legacy.buildBriefSnapshot,
    buildConsistencySnapshot: legacy.buildConsistencySnapshot,
    buildConvictionCalibrationSnapshot: legacy.buildConvictionCalibrationSnapshot,
    buildCurrentBucketRiskBands: legacy.buildCurrentBucketRiskBands,
    buildDecisionImpactMarketStats: legacy.buildDecisionImpactMarketStats,
    buildDecisionImpactThemeStats: legacy.buildDecisionImpactThemeStats,
    buildDecisionStack: legacy.buildDecisionStack,
    buildEdgeDiagnosticsReport: legacy.buildEdgeDiagnosticsReport,
    buildEdgeQualityCalibrationFromSnapshot: legacy.buildEdgeQualityCalibrationFromSnapshot,
    buildEdgeQualityCalibrationSnapshot: legacy.buildEdgeQualityCalibrationSnapshot,
    buildHistoricalOpportunitySnapshot: legacy.buildHistoricalOpportunitySnapshot,
    buildInvalidationRules: legacy.buildInvalidationRules,
    buildOpportunityFallbackSnapshot: legacy.buildOpportunityFallbackSnapshot,
    buildOpportunityLedgerProjection: buildOpportunityLedgerProjectionData,
    buildOpportunitySnapshot: legacy.buildOpportunitySnapshot,
    buildPolicyStateSnapshot: legacy.buildPolicyStateSnapshot,
    buildPlanFallbackPayload: legacy.buildPlanFallbackPayload,
    buildTraderPlaybookSnapshot: legacy.buildTraderPlaybookSnapshot,
    buildUncertaintySnapshot: legacy.buildUncertaintySnapshot,
    calculatePXI: legacy.calculatePXI,
    calculatePXISignal: legacy.calculatePXISignal,
    calibrationQualityForSampleSize: legacy.calibrationQualityForSampleSize,
    canSendEmail: legacy.canSendEmail,
    clamp: legacy.clamp,
    computeCalibrationDiagnostics: legacy.computeCalibrationDiagnostics,
    computeEdgeQualitySnapshot: legacy.computeEdgeQualitySnapshot,
    computeFreshnessDiagnostics: legacy.computeFreshnessDiagnostics,
    computeFreshnessStatus: legacy.computeFreshnessStatus,
    computeRiskSizingSnapshot: legacy.computeRiskSizingSnapshot,
    claimMarketRefreshRun: claimMarketRefreshRunData,
    computeFreshnessSloWindow: computeFreshnessSloWindowData,
    computeNextExpectedRefresh: computeNextExpectedRefreshModule,
    computeUtilityFunnelSummary: computeUtilityFunnelSummaryData,
    constantTimeEquals: constantTimeCompare,
    detectDivergence: legacy.detectDivergence,
    detectRegime: legacy.detectRegime,
    enforceAdminAuth: enforceAdminRouteAuth,
    ensureMarketProductSchema: ensureMarketProductSchemaGuard,
    evaluateOpportunityCtaState: legacy.evaluateOpportunityCtaState,
    extractLSTMFeatures: legacy.extractLSTMFeatures,
    extractMLFeatures: legacy.extractMLFeatures,
    fetchAllIndicators: legacy.fetchAllIndicators,
    fetchCalibrationSnapshotAtOrBefore: fetchCalibrationSnapshotAtOrBeforeData,
    fetchDecisionImpactSnapshotAtOrBefore: fetchDecisionImpactSnapshotAtOrBeforeData,
    fetchLatestCalibrationSnapshot: fetchLatestCalibrationSnapshotData,
    fetchLatestConsistencyCheck: fetchLatestConsistencyCheckData,
    fetchPredictionEvaluationSampleSize: legacy.fetchPredictionEvaluationSampleSize,
    formatDate: legacy.formatDate,
    freshnessPenaltyCount: legacy.freshnessPenaltyCount,
    generateEmbeddingText: legacy.generateEmbeddingText,
    generateToken: legacy.generateToken,
    getAlertsSigningSecret: legacy.getAlertsSigningSecret,
    getEmbeddingVector: legacy.getEmbeddingVector,
    hashToken: legacy.hashToken,
    insertMarketEvents: insertMarketEventsData,
    insertOpportunityItemLedgerRow: insertOpportunityItemLedgerRowData,
    insertOpportunityLedgerRow: insertOpportunityLedgerRowData,
    insertUtilityEvent: insertUtilityEventData,
    isBriefSnapshotCompatible: isBriefSnapshotCompatibleModule,
    isChronicStaleness: legacy.isChronicStaleness,
    isFeatureEnabled: legacy.isFeatureEnabled,
    latestDateInSeries: legacy.latestDateInSeries,
    loadLSTMModel: legacy.loadLSTMModel,
    loadMLModel: legacy.loadMLModel,
    loadSPYReturnModel: legacy.loadSPYReturnModel,
    lstmForward: legacy.lstmForward,
    MINIMUM_RELIABLE_SAMPLE: legacy.MINIMUM_RELIABLE_SAMPLE,
    normalizeAlertTypes: legacy.normalizeAlertTypes,
    normalizeCadence: legacy.normalizeCadence,
    normalizeOpportunityItemsForPublishing: legacy.normalizeOpportunityItemsForPublishing,
    normalizeUtilityActionabilityState: legacy.normalizeUtilityActionabilityState,
    normalizeUtilityEventType: legacy.normalizeUtilityEventType,
    normalizeUtilityRoute: legacy.normalizeUtilityRoute,
    normalizeUtilitySessionId: legacy.normalizeUtilitySessionId,
    parseBackfillDateRange: legacy.parseBackfillDateRange,
    parseBackfillLimit: legacy.parseBackfillLimit,
    parseIsoDate: legacy.parseIsoDate,
    parseJsonBody: legacy.parseJsonBody,
    predictSPYReturn: legacy.predictSPYReturn,
    priceOnOrAfterSeries: legacy.priceOnOrAfterSeries,
    projectOpportunityFeed: legacy.projectOpportunityFeed,
    recordMarketRefreshRunFinish: recordMarketRefreshRunFinishData,
    recordMarketRefreshRunStart: recordMarketRefreshRunStartData,
    resolveConflictState: legacy.resolveConflictState,
    resolveDecisionImpactGovernance: legacy.resolveDecisionImpactGovernance,
    resolveHorizonBias: legacy.resolveHorizonBias,
    resolveLatestRefreshTimestamp: resolveLatestRefreshTimestampData,
    resolvePlanActionability: legacy.resolvePlanActionability,
    resolveStalePolicy: legacy.resolveStalePolicy,
    resolveThemeProxyRules: legacy.resolveThemeProxyRules,
    roundMetric: legacy.roundMetric,
    sanitizeUtilityPayload: legacy.sanitizeUtilityPayload,
    sendCloudflareEmail: legacy.sendCloudflareEmail,
    reserveDigestDeliveryForSubscriber: reserveDigestDeliveryForSubscriberService,
    finalizeDigestDeliverySent: finalizeDigestDeliverySentService,
    finalizeDigestDeliveryFailure: finalizeDigestDeliveryFailureService,
    sendDigestToSubscriber: sendDigestToSubscriberService,
    stableHash: legacy.stableHash,
    storeBriefSnapshot: storeBriefSnapshotData,
    storeCalibrationSnapshot: storeCalibrationSnapshotData,
    storeConsistencyCheck: storeConsistencyCheckData,
    storeDecisionImpactSnapshot: storeDecisionImpactSnapshotData,
    storeOpportunitySnapshot: storeOpportunitySnapshotData,
    summarizeCrossHorizonCoherence: legacy.summarizeCrossHorizonCoherence,
    toNumber: legacy.toNumber,
    validateEmail: legacy.validateEmail,
    xgbPredict: legacy.xgbPredict,
  };
}

export type WorkerRouteDeps = ReturnType<typeof createRouteDeps>;
