import type { IndicatorDefinition } from '../types/indicators.js';

export const INDICATORS: IndicatorDefinition[] = [
  // ============== POSITIONING (15%) - v1.1: was Liquidity 22% ==============
  {
    id: 'fed_balance_sheet',
    name: 'Fed Balance Sheet',
    category: 'positioning',
    source: 'fred',
    ticker: 'WALCL',
    frequency: 'weekly',
    normalization: 'percentile',
    inverted: false,
    description: 'Total assets held by Federal Reserve',
  },
  {
    id: 'treasury_general_account',
    name: 'Treasury General Account',
    category: 'positioning',
    source: 'fred',
    ticker: 'WTREGEN',
    frequency: 'weekly',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'TGA balance - drains liquidity when high',
  },
  {
    id: 'reverse_repo',
    name: 'Reverse Repo Facility',
    category: 'positioning',
    source: 'fred',
    ticker: 'RRPONTSYD',
    frequency: 'daily',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'RRP usage - liquidity parked at Fed',
  },
  {
    id: 'net_liquidity',
    name: 'Net Liquidity',
    category: 'positioning',
    source: 'fred',
    ticker: 'WALCL-WTREGEN-RRPONTSYD',
    frequency: 'weekly',
    normalization: 'percentile',
    inverted: false,
    description: 'Fed assets less Treasury General Account and reverse-repo balances',
  },

  // ============== CREDIT SPREADS (20%) ==============
  {
    id: 'hy_oas_spread',
    name: 'High Yield OAS Spread',
    category: 'credit',
    source: 'fred',
    ticker: 'BAMLH0A0HYM2',
    frequency: 'daily',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'HY corporate bond spread over treasuries',
  },
  {
    id: 'ig_oas_spread',
    name: 'Investment Grade OAS Spread',
    category: 'credit',
    source: 'fred',
    ticker: 'BAMLC0A0CM',
    frequency: 'daily',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'IG corporate bond spread over treasuries',
  },
  {
    id: 'yield_curve_2s10s',
    name: '2s10s Yield Curve',
    category: 'credit',
    source: 'fred',
    ticker: 'T10Y2Y',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: '10Y minus 2Y treasury spread',
  },
  {
    id: 'bbb_aaa_spread',
    name: 'BBB-AAA Spread',
    category: 'credit',
    source: 'fred',
    ticker: 'BAMLC0A4CBBB',
    frequency: 'daily',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'Credit quality spread within IG',
  },

  // ============== VOLATILITY & SENTIMENT (20%) ==============
  {
    id: 'vix',
    name: 'VIX',
    category: 'volatility',
    source: 'yahoo',
    ticker: '^VIX',
    frequency: 'realtime',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'CBOE Volatility Index',
  },
  {
    id: 'vix_term_structure',
    name: 'VIX Term Structure',
    category: 'volatility',
    source: 'yahoo',
    ticker: '^VIX,^VIX3M',
    frequency: 'daily',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'VIX - VIX3M spread (contango = bullish)',
  },
  {
    id: 'aaii_sentiment',
    name: 'Risk Sentiment Proxy',
    category: 'volatility',
    source: 'calculated',
    ticker: 'CNN_FEAR_GREED_MINUS_50',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'CNN Fear & Greed score centered at zero; not AAII survey data',
  },
  {
    id: 'gex',
    name: 'Volatility-Surface Proxy',
    category: 'volatility',
    source: 'calculated',
    ticker: 'VIX_TERM_PROXY',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'Derived volatility-surface regime proxy; not dealer gamma exposure',
  },

  // ============== MARKET BREADTH (15%) ==============
  {
    id: 'rsp_spy_ratio',
    name: 'RSP/SPY Ratio',
    category: 'breadth',
    source: 'yahoo',
    ticker: 'RSP,SPY',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'Equal weight vs cap weight S&P 500',
  },
  {
    id: 'sector_breadth',
    name: 'Sector Breadth',
    category: 'breadth',
    source: 'calculated',
    ticker: 'XLK,XLF,XLV,XLE,XLI,XLC,XLY,XLP,XLU,XLB,XLRE',
    frequency: 'daily',
    normalization: 'direct',
    inverted: false,
    description: 'Percent of sector ETFs with positive momentum',
  },
  {
    id: 'small_cap_strength',
    name: 'Small Cap Relative Strength',
    category: 'breadth',
    source: 'yahoo',
    ticker: 'IWM,SPY',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'Small cap (IWM) vs large cap (SPY) ratio',
  },
  {
    id: 'midcap_strength',
    name: 'Mid Cap Relative Strength',
    category: 'breadth',
    source: 'yahoo',
    ticker: 'IJH,SPY',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'Mid cap (IJH) vs large cap (SPY) ratio',
  },

  // ============== MACRO ECONOMIC (10%) ==============
  {
    id: 'ism_manufacturing',
    name: 'Manufacturing Payrolls',
    category: 'macro',
    source: 'fred',
    ticker: 'MANEMP',
    frequency: 'monthly',
    normalization: 'percentile',
    inverted: false,
    description: 'Manufacturing employees, thousands (FRED MANEMP); legacy internal ID retained for history compatibility',
  },
  {
    id: 'jobless_claims',
    name: 'Initial Jobless Claims (4wk)',
    category: 'macro',
    source: 'fred',
    ticker: 'IC4WSA',
    frequency: 'weekly',
    normalization: 'percentile_inverted',
    inverted: true,
    description: '4-week moving average of initial claims',
  },
  {
    id: 'cfnai',
    name: 'Chicago Fed National Activity',
    category: 'macro',
    source: 'fred',
    ticker: 'CFNAI',
    frequency: 'monthly',
    normalization: 'zscore',
    inverted: false,
    description: 'Broad economic activity index',
  },

  // ============== GLOBAL RISK APPETITE (10%) ==============
  {
    id: 'dxy',
    name: 'DXY Dollar Index',
    category: 'global',
    source: 'yahoo',
    ticker: 'DX-Y.NYB',
    frequency: 'realtime',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'US Dollar Index (weak dollar = risk-on)',
  },
  {
    id: 'copper_gold_ratio',
    name: 'Copper/Gold Ratio',
    category: 'global',
    source: 'yahoo',
    ticker: 'HG=F,GC=F',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'Dr. Copper vs Gold ratio',
  },
  {
    id: 'em_spread',
    name: 'EM Bond Spread',
    category: 'global',
    source: 'fred',
    ticker: 'BAMLEMCBPIOAS',
    frequency: 'daily',
    normalization: 'percentile_inverted',
    inverted: true,
    description: 'Emerging market bond spread',
  },
  {
    id: 'audjpy',
    name: 'AUD/JPY',
    category: 'global',
    source: 'yahoo',
    ticker: 'AUDJPY=X',
    frequency: 'realtime',
    normalization: 'percentile',
    inverted: false,
    description: 'Carry trade proxy',
  },

  // ============== CRYPTO / BITCOIN (10%) ==============
  {
    id: 'btc_vs_200dma',
    name: 'BTC vs 200 DMA',
    category: 'crypto',
    source: 'yahoo',
    ticker: 'BTC-USD',
    frequency: 'daily',
    normalization: 'direct',
    inverted: false,
    description: 'Bitcoin price relative to 200-day MA',
  },
  {
    id: 'btc_price',
    name: 'Bitcoin Price',
    category: 'crypto',
    source: 'yahoo',
    ticker: 'BTC-USD',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'Bitcoin spot price in US dollars',
  },
  {
    id: 'stablecoin_mcap',
    name: 'Stablecoin Market Cap',
    category: 'crypto',
    source: 'defillama',
    ticker: 'STABLECOINS',
    frequency: 'daily',
    normalization: 'percentile',
    inverted: false,
    description: 'Total stablecoin market cap growth',
  },
];

export const getIndicatorsBySource = (source: string): IndicatorDefinition[] =>
  INDICATORS.filter((i) => i.source === source);

export const getIndicatorsByCategory = (category: string): IndicatorDefinition[] =>
  INDICATORS.filter((i) => i.category === category);

export const getIndicatorById = (id: string): IndicatorDefinition | undefined =>
  INDICATORS.find((i) => i.id === id);
